/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo57.Vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import universidadgrupo57.AccesoADatos.AlumnoData;
import universidadgrupo57.Entidades.Alumno;

public class AlumnoView extends javax.swing.JFrame {

    private AlumnoData aluData = new AlumnoData();
    private Alumno alumnoActual=null;

    public AlumnoView() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBsalir = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBnuevo = new javax.swing.JButton();
        jDateFechaN = new com.toedter.calendar.JDateChooser();
        estadoRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTapellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTdni = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(416, 335));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(416, 335));
        jPanel1.setPreferredSize(new java.awt.Dimension(416, 335));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBsalir.setBackground(new java.awt.Color(51, 153, 255));
        jBsalir.setText("Salir");
        jBsalir.setBorder(null);
        jBsalir.setBorderPainted(false);
        jBsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 50, 30));

        jBguardar.setBackground(new java.awt.Color(51, 153, 255));
        jBguardar.setText("Guardar");
        jBguardar.setBorder(null);
        jBguardar.setBorderPainted(false);
        jBguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 70, 30));

        jBeliminar.setBackground(new java.awt.Color(51, 153, 255));
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(null);
        jBeliminar.setBorderPainted(false);
        jBeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 70, 30));

        jBnuevo.setBackground(new java.awt.Color(51, 153, 255));
        jBnuevo.setText("Nuevo");
        jBnuevo.setBorder(null);
        jBnuevo.setBorderPainted(false);
        jBnuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jBnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 60, 30));
        jPanel1.add(jDateFechaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 110, -1));

        estadoRadioButton.setBorder(null);
        estadoRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estadoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(estadoRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel6.setText("Fecha de nacimiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel5.setText("Estado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jTapellido.setBorder(null);
        jPanel1.add(jTapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jTnombre.setBorder(null);
        jPanel1.add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 100, 20));

        jBbuscar.setBackground(new java.awt.Color(51, 153, 255));
        jBbuscar.setText("Buscar");
        jBbuscar.setBorder(null);
        jBbuscar.setBorderPainted(false);
        jBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 100, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jTdni.setToolTipText("");
        jTdni.setBorder(null);
        jTdni.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdniActionPerformed(evt);
            }
        });
        jTdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTdniKeyTyped(evt);
            }
        });
        jPanel1.add(jTdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 140, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(416, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(416, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        jLabel1.setText("Alumnos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel2.setText("Documento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 140, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 120, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdniActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        try{
        Integer dni=Integer.parseInt(jTdni.getText());
        String apellido= jTapellido.getText();
        String nombre=jTnombre.getText();
        if(apellido.isEmpty() || nombre.isEmpty()){
            JOptionPane.showMessageDialog(this, "No puede haber campos vacios");
            return;
        
        }
        java.util.Date sfecha=jDateFechaN.getDate();
        LocalDate fechaN=sfecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Boolean estado=estadoRadioButton.isSelected();
        if(alumnoActual==null){
        
            alumnoActual= new Alumno(dni, apellido, nombre, fechaN, estado);
            aluData.guardarAlumno(alumnoActual);
        
        }else{
        
            alumnoActual.setDni(dni);
            alumnoActual.setApellido(apellido);
            alumnoActual.setNombre(nombre);
            alumnoActual.setFechaNacimiento(fechaN);
            aluData.modificarAlumno(alumnoActual);
        
        }
        
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese solo numeros");
        
        }
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        limpiarCampos();
        alumnoActual=null;
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        try{
        Integer dni=Integer.parseInt(jTdni.getText());
        alumnoActual=aluData.buscarAlumnoPorDni(dni);
        if(alumnoActual!=null){
                jTapellido.setText(alumnoActual.getApellido());
                jTnombre.setText(alumnoActual.getNombre());
                estadoRadioButton.setSelected(alumnoActual.isEstado());
                LocalDate lc = alumnoActual.getFechaNacimiento();
                java.util.Date date = java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
                jDateFechaN.setDate(date);
                
            }
        }catch(NumberFormatException ex){
        
            JOptionPane.showMessageDialog(this, "Ingrese solo numeros");
            limpiarCampos();
        }
                
    }//GEN-LAST:event_jBbuscarActionPerformed
       
    
    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        if (alumnoActual!=null){
            aluData.eliminarAlumno(alumnoActual.getIdAlumno());
            alumnoActual=null;
            limpiarCampos();
        }else{
            JOptionPane.showMessageDialog(this, "No ha seleccionado un alumno");
        
        }
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void estadoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoRadioButtonActionPerformed

    private void jTdniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdniKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jTdniKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoView().setVisible(true);
            }
        });
    }

    private void limpiarCampos() {
        jTdni.setText("");
        jTapellido.setText("");
        jTnombre.setText("");
        estadoRadioButton.setSelected(false);
        jDateFechaN.setCalendar(null);
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton estadoRadioButton;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jBsalir;
    private com.toedter.calendar.JDateChooser jDateFechaN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTapellido;
    private javax.swing.JTextField jTdni;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables
}
