/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo57.Vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import universidadgrupo57.AccesoADatos.AlumnoData;
import universidadgrupo57.AccesoADatos.InscripcionData;
import universidadgrupo57.AccesoADatos.MateriaData;
import universidadgrupo57.Entidades.Alumno;
import universidadgrupo57.Entidades.Inscripcion;
import universidadgrupo57.Entidades.Materia;


public class InscripcionView extends javax.swing.JFrame {

    /**
     * Creates new form Inscripcion
     */
    
    private List<Materia> listaM;
    private List<Alumno> listaA;
    private InscripcionData inscData;
    private MateriaData mData;
    private AlumnoData aData;
    
    private DefaultTableModel modelo;
     
    public InscripcionView() {
        initComponents();
        aData = new AlumnoData();
        listaA = aData.listarAlumnos();
        modelo = new DefaultTableModel();
        inscData = new InscripcionData();
        mData = new MateriaData();
        cargaAlumnos();
        armarCabeceraTabla();
        
        jBanularInscripcion.setEnabled(false);
        jBinscribir.setEnabled(false);
        
        
        
        
        
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBsalir = new javax.swing.JButton();
        jBanularInscripcion = new javax.swing.JButton();
        jBinscribir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMaterias = new javax.swing.JTable();
        materiasNoInscriptas = new javax.swing.JRadioButton();
        materiasInscriptas = new javax.swing.JRadioButton();
        alumnoComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(416, 335));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBsalir.setBackground(new java.awt.Color(51, 153, 255));
        jBsalir.setText("Salir");
        jBsalir.setBorder(null);
        jBsalir.setBorderPainted(false);
        jBsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 60, 30));

        jBanularInscripcion.setBackground(new java.awt.Color(51, 153, 255));
        jBanularInscripcion.setText("Anular Inscripcion");
        jBanularInscripcion.setBorder(null);
        jBanularInscripcion.setBorderPainted(false);
        jBanularInscripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBanularInscripcion.setEnabled(false);
        jBanularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanularInscripcionActionPerformed(evt);
            }
        });
        jPanel1.add(jBanularInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 110, 30));

        jBinscribir.setBackground(new java.awt.Color(51, 153, 255));
        jBinscribir.setText("Inscribir");
        jBinscribir.setBorder(null);
        jBinscribir.setBorderPainted(false);
        jBinscribir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBinscribir.setEnabled(false);
        jBinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinscribirActionPerformed(evt);
            }
        });
        jPanel1.add(jBinscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 80, 30));

        tablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Anõ"
            }
        ));
        tablaMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMaterias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 380, 100));

        materiasNoInscriptas.setBorder(null);
        materiasNoInscriptas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        materiasNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiasNoInscriptasActionPerformed(evt);
            }
        });
        jPanel1.add(materiasNoInscriptas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        materiasInscriptas.setBorder(null);
        materiasInscriptas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        materiasInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiasInscriptasActionPerformed(evt);
            }
        });
        jPanel1.add(materiasInscriptas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        alumnoComboBox.setBorder(null);
        alumnoComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alumnoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(alumnoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 180, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        jLabel3.setText("Inscripciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel1.setText("Seleccione un alumno");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel4.setText("Materias inscriptas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 110, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel2.setText("Materias No inscriptas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void materiasInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiasInscriptasActionPerformed
        borrarFilaTabla();
        materiasNoInscriptas.setSelected(false);
        cargaDatosInscriptas();
        jBinscribir.setEnabled(false);
        jBanularInscripcion.setEnabled(true);
        
            
    }//GEN-LAST:event_materiasInscriptasActionPerformed

    private void jBanularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanularInscripcionActionPerformed
        int filaselec = tablaMaterias.getSelectedRow();
        if(filaselec!= -1){
            Alumno a=(Alumno)alumnoComboBox.getSelectedItem();
            int idMateria=(Integer)modelo.getValueAt(filaselec, 0);
            inscData.borrarInscripcion(a.getIdAlumno(), idMateria);
            borrarFilaTabla();
        }
    }//GEN-LAST:event_jBanularInscripcionActionPerformed

    private void alumnoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoComboBoxActionPerformed
             
            
            
        
    }//GEN-LAST:event_alumnoComboBoxActionPerformed

    private void tablaMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMateriasMouseClicked
        
        
        if(materiasInscriptas.isSelected()) {
            jBanularInscripcion.setEnabled(true);
            jBinscribir.setEnabled(false);
                
        } else {
            jBanularInscripcion.setEnabled(false);
            jBinscribir.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_tablaMateriasMouseClicked

    private void materiasNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiasNoInscriptasActionPerformed
        borrarFilaTabla();
        materiasInscriptas.setSelected(false);
        cargaDatosNoInscriptas();
        jBanularInscripcion.setEnabled(false);
        jBinscribir.setEnabled(true);
        
        

        
    }//GEN-LAST:event_materiasNoInscriptasActionPerformed

    private void jBinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinscribirActionPerformed
        int filaselec = tablaMaterias.getSelectedRow();
        if(filaselec!= -1){
            Alumno a=(Alumno)alumnoComboBox.getSelectedItem();
            
            int idMateria=(Integer)modelo.getValueAt(filaselec, 0);
            String nombreMateria=(String)modelo.getValueAt(filaselec, 1);
            int anio=(Integer)modelo.getValueAt(filaselec, 2);
            Materia m=new Materia(idMateria, nombreMateria, anio, true);
            Inscripcion i= new Inscripcion(a,m,0);
            inscData.guardarInscripcion(i);
            borrarFilaTabla();
    }//GEN-LAST:event_jBinscribirActionPerformed
    }
    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed
private void cargaAlumnos(){

    for (Alumno item : listaA) {
        alumnoComboBox.addItem(item);
    }

}

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Año");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        tablaMaterias.setModel(modelo);
        
    }
    
    private void borrarFilaTabla(){
        int indice =modelo.getRowCount() -1;
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    
    }
    
    private void cargaDatosNoInscriptas() {
        borrarFilaTabla();
        Alumno selec = (Alumno) alumnoComboBox.getSelectedItem();
        listaM = inscData.obtenerMateriasNOCursadas(selec.getIdAlumno());
        for (Materia m : listaM) {
            modelo.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAnio()});

        }

    }
    
    private void cargaDatosInscriptas(){
        borrarFilaTabla();
        Alumno selec = (Alumno)alumnoComboBox.getSelectedItem();
        List<Materia> lista= inscData.obtenerMateriasCursadas(selec.getIdAlumno());
        for (Materia m : lista) {
            modelo.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAnio()});
        }
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscripcionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> alumnoComboBox;
    private javax.swing.JButton jBanularInscripcion;
    private javax.swing.JButton jBinscribir;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton materiasInscriptas;
    private javax.swing.JRadioButton materiasNoInscriptas;
    private javax.swing.JTable tablaMaterias;
    // End of variables declaration//GEN-END:variables
}
